package com.model;

import java.util.*;


//CONSTANT STATIC FILES THAT WILL BE USED THROUGHOUT THE PROJECT

public class K {
    public  static int messageSize;
    public static String tutor = "RAHIEME SAMUELS";
    public static Map<String , Double> senderList = new HashMap<>();
    //LIST TO STORE QUESTION
    public static List<Message> questionList = new ArrayList<>();
    //DATA STRUCTURE TO STORE ANSWERS
    public static Queue<Message> answerList = new LinkedList<>();


    //WORDLIST OF THE TOP 100 MOST COMMON ENGLISH WORDS
    public static  final String[] wordList =
                    {"have" ,
                    "that" ,
                    "for" ,
                    "you" ,
                    "with" ,
                    "say" ,
                    "this",
                    "they",
                    "but" ,
                    "his" ,
                    "from" ,
                    "not" ,
                    "she" ,
                    "as" ,
                    "what" ,
                    "their" ,
                    "can",
                    "who," ,
                    "get" ,
                    "would," ,
                    "her",
                    "all" ,
                    "make" ,
                    "about" ,
                    "know" ,
                    "will" ,
                    "one" ,
                    "time" ,
                    "there" ,
                    "year" ,
                    "think" ,
                    "when" ,
                    "which" ,
                    "them" ,
                    "some" ,
                    "people" ,
                    "take" ,
                    "out" ,
                    "into" ,
                    "just" ,
                    "see" ,
                    "him" ,
                    "your" ,
                    "come" ,
                    "could" ,
                    "now" ,
                    "than" ,
                    "like" ,
                    "other" ,
                    "how" ,
                    "then" ,
                    "its" ,
                    "our" ,
                    "two" ,
                    "more" ,
                    "these" ,
                    "want" ,
                    "way" ,
                    "look" ,
                    "first" ,
                    "also" ,
                    "new" ,
                    "because" ,
                    "day" ,
                    "use" ,
                    "man" ,
                    "find" ,
                    "here" ,
                    "thing" ,
                    "give" ,
                    "many" ,
                    "well" ,
                    "only" ,
                    "those" ,
                    "tell" ,
                    "very" ,
                    "even" ,
                    "back" ,
                    "any" ,
                    "good" ,
                    "woman" ,
                    "through" ,
                    "life" ,
                    "child" ,
                    "work" ,
                    "down" ,
                    "may" ,
                    "after" ,
                    "should" ,
                    "call" ,
                    "world" ,
                    "over" ,
                    "school" ,
                    "still" ,
                    "try" ,
                    "last" ,
                    "ask",
                            "maybe"
            };
}
